opencost:
  customPricing:
    enabled: true
    provider: custom
    costModel:
      description: Custom pricing configuration
      CPU: 0.03
      spotCPU: 0.006
      RAM: 0.004
      spotRAM: 0.0008
      storage: 0.00005
  exporter:
    defaultClusterId: test-cl01
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
  ui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations: 
        cert-manager.io/cluster-issuer: "local-ca-issuer"
      hosts:
        - host: opencost.test-cl01.local
          paths:
            - /
      servicePort: http-ui
      tls:
        - secretName: opencost-tls
          hosts:
            - opencost.test-cl01.local
  metrics:
    serviceMonitor:
      enabled: true
      namespace: monitoring

  prometheus:
    internal:
      enabled: true
      serviceName: monitoring-kube-prometheus-prometheus
      namespaceName: monitoring
      port: 9090

