rvn-mysql:
  auth:
    user: webapp
    password: webapp
    rootPassword: supersecurepassword
    database: webapp
  persistence:
    accessMode: ReadWriteOnce
    size: 20Gi
    storageClassName: standard

rvn-usershell:
  mysqlClient:
    auth:
      username: webapp
      password: webapp
      database: webapp
  persistence:
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  securityContext:
    allowPrivilegeEscalation: true
    runAsUser: 1000
    fsGroup: 1000
    readOnlyRootFileSystem: false


rvn-webrunner:
  enabled: false

rvn-frankenphp:
  enabled: true
  replicaCount: 1
  ingress:
    className: nginx
    hosts:
      - revan.test-cl01.local
    tls:
      certIssuer: local-ca-issuer
      enabled: true
  persistence:
    accessMode: ReadWriteOnce
    size: 20Gi
    storageClass: standard

rvn-mta:
  replicaCount: 1


