controller:
  ingressClassResource:
    name: nginx
  ingressClass: nginx
  kind: DaemonSet
  hostNetwork: true
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  config:
    enable-underscores-in-headers: true
    hsts: "false"
  service:
    type: ClusterIP
