global:
  edition: ce
  hosts:
    domain: test-cl01.local

  ingress:
    class: nginx
    configureCertmanager: false
    annotations:
      cert-manager.io/cluster-issuer: local-ca-issuer
    tls:
      enabled: true

  certmanager-issuer:
    email: dev@localhost

postgresql:
  install: true

redis:
  install: true

certmanager:
  installCRDs: false
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab:
  kas:
    ingress:
      tls:
        secretName: kas-ca-key
  webservice:
    ingress:
      tls:
        secretName: webservice-ca-key

registry:
  ingress:
    tls:
      secretName: registry-ca-key 

minio:
  ingress:
    tls:
      secretName: minio-ca-key
