global:
  edition: ce
  hosts:
    domain: test-cl01.local
    ssh: gitlab.test-cl01.local

  ingress:
    class: nginx
    configureCertmanager: false
    annotations:
      cert-manager.io/cluster-issuer: local-ca-issuer
    tls:
      enabled: true

  certmanager-issuer:
    email: dev@localhost

  shell:
    port: 22

postgresql:
  install: true

redis:
  install: true

certmanager:
  installCRDs: false
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab:
  kas:
    ingress:
      tls:
        secretName: kas-ca-key
  webservice:
    ingress:
      tls:
        secretName: webservice-ca-key
  gitlab-shell:
    enabled: true
    service:
      type: NodePort
      nodePort: 30022
    port: 22

registry:
  ingress:
    tls:
      secretName: registry-ca-key 

minio:
  ingress:
    tls:
      secretName: minio-ca-key

gitlab-runner:
  runners:
    privileged: true
    config: |
      [[runners]]
        name = "kubernetes-runner"
        url = "https://gitlab.test-cl01.local/"