global:
  edition: ce
  hosts:
    domain: ${DOMAIN}
    ssh: gitlab.${DOMAIN}

  ingress:
    class: nginx
    configureCertmanager: false
    annotations:
      cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER_NAME}
    tls:
      enabled: true

  certmanager-issuer:
    email: dev@localhost

  shell:
    port: 22

postgresql:
  install: true

redis:
  install: true

certmanager:
  installCRDs: false
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab:
  kas:
    ingress:
      tls:
        secretName: kas-ca-key
  webservice:
    ingress:
      tls:
        secretName: webservice-ca-key
  gitlab-shell:
    enabled: true
    service:
      type: NodePort
      nodePort: 30022
    port: 22

registry:
  ingress:
    tls:
      secretName: registry-ca-key 

minio:
  ingress:
    tls:
      secretName: minio-ca-key

gitlab-runner:
  gitlabUrl: http://gitlab-webservice-default:8080
  runners:
    privileged: true
